### ISSUE TITLE
Major (mobile)  - main page - настроить отображение меню

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/hub#29]
![image](https://user-images.githubusercontent.com/36338626/231849130-9fc403e4-bbca-450c-aa9e-fefd697a9022.png)
сейчас приходится скролить что бы найти нижню часть

**Comment by bageus** [comment]
это то что ты мне писал что даже на форумах решения нет - точнее не использовать сафари - пока оставляем - я себе пометил как question

**Comment by hoolisoftware** [comment]
> это то что ты мне писал что даже на форумах решения нет - точнее не использовать сафари - пока оставляем - я себе пометил как question

Решение есть) и я даже отправил его вам

Но оно сомнительное, поэтому нужно будет поискать ещё
