### ISSUE TITLE
Major - info - работу перехода между меню

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/hub#39]
При открытой вкладке info если нажать на кошелек, кошелек не открывается
<img width="1113" alt="Снимок экрана 2023-04-16 в 14 33 13" src="https://user-images.githubusercontent.com/36338626/232315055-b196ec74-b4c6-4ec9-9413-4c8702327d54.png">

**Comment by hoolisoftware** [comment]
Что за кошелёк не открывается?

**Comment by bageus** [comment]
записал тебе видео
